using System;
using System.Collections.Generic;
using System.Text;

namespace Sistema.Entidades.Clientes
{
    public class Socio
    {

        public int NROSOCIO { get; set; }
        public long RUT { get; set; }
        public string DVRUT { get; set; }
        public string NROSERIE { get; set; }
        public byte PERSONA { get; set; }
        public byte VALIDO { get; set; }
        public string Tipo { get; set; }
        public string CATEGORIA { get; set; }
        public long Nrocuenta { get; set; }
        public string Digcuenta { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Nombres { get; set; }
        public string NombreCorto { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string FechaIng { get; set; }
        public string FechaEgr { get; set; }
        public string Sexo { get; set; }
        public int Region { get; set; }
        public string Ciudad { get; set; }
        public string SECTOR { get; set; }
        public string FechaNac { get; set; }
        public int Estado { get; set; }
        public int TipoViv { get; set; }
        public string Email { get; set; }
        public string FechaSolicitud { get; set; }
        public string EstadoCivil { get; set; }
        public string MOTIVO { get; set; }
        public long SUELDOLIQUIDO { get; set; }
        public long RutConyuge { get; set; }
        public string DvRutConyuge { get; set; }
        public string NomConyuge { get; set; }
        public string NomEmpresa { get; set; }
        public string MotivoIncorpora { get; set; }
        public string FechaContrato { get; set; }
        public string SocioSiNo { get; set; }
        public int AnoContrato { get; set; }
        public int NHIJOS { get; set; }
        public int ANOHIJO1 { get; set; }
        public int ANOHIJO2 { get; set; }
        public int ANOHIJO3 { get; set; }
        public int ANOHIJO4 { get; set; }
        public int ANOHIJO5 { get; set; }
        public int ANOHIJO6 { get; set; }
        public int CantCargas { get; set; }
        public string Celular { get; set; }
        public int Compa { get; set; }
        public long Dividendo { get; set; }
        public int FamRenta { get; set; }
        public string LaboCiudad { get; set; }
        public string LaboDireccion { get; set; }
        public string LaboEmail { get; set; }
        public int LaboRegion { get; set; }
        public string LaboSector { get; set; }
        public string LaboTelefono { get; set; }
        public string LaboVilla { get; set; }
        public long LiquidoPension { get; set; }
        public string Profesion { get; set; }
        public long RefRut { get; set; }
        public string RefDvRut { get; set; }
        public string RefCelular { get; set; }
        public string RefCiudad { get; set; }
        public int RefCompa { get; set; }
        public string RefDireccion { get; set; }
        public string RefEmail { get; set; }
        public string RefMaterno { get; set; }
        public string RefNombres { get; set; }
        public string RefPaterno { get; set; }
        public int RefRegion { get; set; }
        public string RefSECTOR { get; set; }
        public string RefTelefono { get; set; }
        public string RefVilla { get; set; }
        public int Spam { get; set; }
        public int SpamLegal { get; set; }
        public int SpamAGS { get; set; }
        public int Destino { get; set; }
        public int VehiAno { get; set; }
        public int Vehiculo { get; set; }
        public string VehiMarca { get; set; }
        public string VehiModelo { get; set; }
        public string VehiPatente { get; set; }
        public string Villa { get; set; }
        public int CODINST { get; set; }
        public string Comentario { get; set; }
        public int FUSION { get; set; }
        public int SUCURSAL { get; set; }
        public string FECHAING_COOP { get; set; }
        public string OCUPACION { get; set; }
        public string COBRADOR { get; set; }
        public int COOPERATIVA { get; set; }
        public string RUTRELACION { get; set; }
        public int RELACION { get; set; }
        public string UsuarioCreador { get; set; }
        public string UsuarioModificador { get; set; }
        public string FechaModificado { get; set; }
        public string ABOGADO { get; set; }
        public int ADIC_FAM { get; set; }
        public string CASILLA { get; set; }
        public int DESTINOEMAIL { get; set; }
        public int F_Spam { get; set; }
        public int F_SpamLegal { get; set; }
        public int F_SpamAGS { get; set; }
        public long Nro_Spam { get; set; }
        public long Nro_SpamLegal { get; set; }
        public long Nro_SpamAGS { get; set; }
        public string Cod_Presocio { get; set; }
        public string GIRO { get; set; }
        public int CODACTECO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string VENDEDOR { get; set; }
        public string CLAVE_PROVISORIA { get; set; }
        public string Titular { get; set; }
        public int AdicionalDe { get; set; }
        public string HISTORIA { get; set; }
        public int NUMEROSOCIO { get; set; }
        public string CUENTAPENSION { get; set; }
        public int TIPOBENE { get; set; }
        public string RUTREP2 { get; set; }
        public string NOMREP2 { get; set; }
        public int CODCOMPOSI { get; set; }
        public int CODCIIU { get; set; }
        public int NOUSAEMAIL { get; set; }
        public int ESTATURA { get; set; }
        public int PESO { get; set; }
        public string CONFIRMADO { get; set; }
        public string FECHACONSEJO { get; set; }
        public string ACTARENUNCIA { get; set; }
    }
}
